/**
 * models/StreamEvent.js
 *
 * MongoDB model for real-time pipeline streaming events.
 *
 * WHAT THIS IS:
 * When a query takes 5-20s, instead of showing a loading spinner we stream
 * real-time pipeline status to the frontend via SSE (Server-Sent Events).
 *
 * Each pipeline step emits an event:
 *   { type: "step", message: "🔍 Searching workspace...", tool: "semantic_search" }
 *   { type: "step", message: "⚡ Running SQL query...", tool: "sql_executor" }
 *   { type: "result", message: "Found 5 relevant chunks", data: {...} }
 *   { type: "done", message: "Answer ready" }
 *   { type: "error", message: "Something went wrong" }
 *
 * AUTO-CLEANUP:
 * TTL index auto-deletes stream documents after 1 hour.
 * No cron job needed — MongoDB handles it natively.
 *
 * WORKSPACE ISOLATION:
 * Each stream is scoped to (workspaceId + sessionId).
 * Users can only read their own streams.
 */

const mongoose = require('mongoose');

const streamEventSchema = new mongoose.Schema({
    // Unique session ID for this query (generated by Node.js, passed to Python)
    sessionId: {
        type: String,
        required: true,
        index: true
    },

    // Workspace isolation — users can only read their own streams
    workspaceId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Workspace',
        required: true,
        index: true
    },

    // userId for extra isolation layer
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },

    // List of pipeline events in order
    events: [{
        // Event type
        type: {
            type: String,
            enum: ['step', 'result', 'answer_chunk', 'done', 'error'],
            required: true
        },
        // Human-readable message shown to user
        message: {
            type: String,
            required: true
        },
        // Which tool/step emitted this (for frontend icon/color)
        tool: {
            type: String,
            enum: [
                'router',           // Intent classification
                'sql_generator',    // SQL generation
                'sql_executor',     // SQL execution
                'semantic_search',  // Vector search
                'reranker',         // Flashrank reranking
                'llm',              // Final LLM answer
                'memory',           // Conversation memory
                'cache',            // Cache hit
                'system'            // General system message
            ],
            default: 'system'
        },
        // Optional structured data (SQL results count, chunk count, etc.)
        data: {
            type: mongoose.Schema.Types.Mixed,
            default: null
        },
        // Timestamp of this event
        timestamp: {
            type: Date,
            default: Date.now
        }
    }],

    // Stream status
    status: {
        type: String,
        enum: ['active', 'completed', 'error'],
        default: 'active'
    },

    // Final answer (stored when done, for non-streaming clients)
    finalAnswer: {
        type: String,
        default: null
    },

    // Intent detected by planner (for UI display)
    intent: {
        type: String,
        default: null
    },

    createdAt: {
        type: Date,
        default: Date.now
    },

    // TTL index: auto-delete after 1 hour (3600 seconds)
    // MongoDB's TTL indexer runs every 60s, so actual deletion may be up to 60s late
    expiresAt: {
        type: Date,
        default: () => new Date(Date.now() + 60 * 60 * 1000), // 1 hour from now
        index: { expireAfterSeconds: 0 }  // TTL index on this field
    }
});

// Compound index for fast lookup by session
streamEventSchema.index({ sessionId: 1, workspaceId: 1 });

module.exports = mongoose.model('StreamEvent', streamEventSchema);
